---
  TRADE_OPTIONS:
    # In your pairing coin --> Cantidad de USDT a comprar
    QUANTITY: 50
    # BTCUSDT will be bought for example 
    PAIRING: USDT
    # How often to check for posts and run the script
    # in minutes
    RUN_EVERY: 0.025
    TEST: True
    SL: 3
    TP: 3
    ENABLE_TSL: True
    TSL: 2
    TTP: 2
